# Default config

# Environment
env = "production"

# HTTP config
[http]
address = ":443" # Listen address (Including colon)
tls = true # Whether TLS is enabled or not (Strongly recommended)
# TLS keypair paths
cert = "/config/tls.cer"
key = "/config/tls.key"

# OpenID config
[openid]
address = "https://demo.identityserver.io" #OpenID server
client_id = "interactive.public" #OpenID client ID
role_path = "resource_access.orange-thallium.roles" #GJSON path to the list of roles (In the identity token)

# OpenID roles config
[openid.roles]
user = "user" # The role required for regular use (Non-administrative actions)

# Vault instance config
[vault]
address = "" # Vault address
# Server CA certificate path (Use one or the other)
ca_cert = "" # Single certificate path
ca_path = "" # Directory of possible certificates
# Mutual TLS keypair paths
client_cert = ""
client_key = ""
insecure = false # Whether to disable TLS verification or not
sni_host = "" # TLS SNI host (Used for multiple TLS certificates)
srv_lookup = false # Whether to lookup SRV records or not
token = "" # Vault token (Should be a locked-down service token)

# MFA config (Unsupported right now)
[mfa]
time_shift = 5 # How far into the future should MFA codes be generated (In seconds)

# Platforms config
[platforms]
# enabled: whether or not the platform is enabled
# key: the absolute Vault secret path

# Epic Games config
[platforms.epic-games]
enabled = true
key = "/secret/orange-thallium/epic-games"

# Steam config
[platforms.steam]
enabled = true
key = "/secret/orange-thallium/steam"

# Riot config
[platforms.riot]
enabled = true
key = "/secret/orange-thallium/riot"
