# Continuous Integration & Deployment
name: CID
on:
  workflow_run:
    branches:
      - 'main'
    workflows:
      - 'Audit'
    types:
      - completed

jobs:
  # Build Docker image and push to the GitHub Container Registry
  github-registry:
    name: Push to the GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    # Run only if security audits passed
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Generate Docker metadata
      - name: Generate Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # Setup QEMU
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to the registry
      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}