# Build and push Docker images
name: Docker
on:
  push:
    branches:
      - "main"

jobs:
  # Build Docker image and push to the GitHub Container Registry
  github-registry:
    name: Push to the GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to the registry
      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ github.repository }}